name = "mayap-alert-worker"
main = "src/index.js"
compatibility_date = "2026-07-17"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "MAYAP_DATA"
id = "THAY_KV_NAMESPACE_ID"

[vars]
PWA_ORIGIN = "https://TEN-GITHUB.github.io"

[triggers]
crons = ["*/1 * * * *"]
