import webpush from "web-push";

const json = (data, status = 200, origin = "*") => new Response(JSON.stringify(data), {status, headers:{"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":origin,"Access-Control-Allow-Headers":"Content-Type, X-Device-ID, X-Device-Key, X-Setup-Code","Access-Control-Allow-Methods":"GET,POST,OPTIONS","Cache-Control":"no-store"}});
const allowedOrigin = (request, env) => env.PWA_ORIGIN || request.headers.get("Origin") || "*";
const cleanId = value => String(value || "").trim().toUpperCase().replace(/[^A-Z0-9_-]/g, "").slice(0, 32);
async function sha256(value){const data=new TextEncoder().encode(value);const digest=await crypto.subtle.digest("SHA-256",data);return [...new Uint8Array(digest)].map(b=>b.toString(16).padStart(2,"0")).join("")}
async function readJson(request){try{return await request.json()}catch{return{}}}
async function getDevice(env,id){const raw=await env.MAYAP_DATA.get(`dev:${id}`);return raw?JSON.parse(raw):null}
async function authDevice(request,env,body={}){const id=cleanId(request.headers.get("X-Device-ID")||body.deviceId),key=request.headers.get("X-Device-Key")||body.deviceKey||"";if(!id||key.length<16)return null;const dev=await getDevice(env,id);if(!dev||dev.keyHash!==await sha256(key))return null;return{id,dev}}
function configurePush(env){webpush.setVapidDetails(env.VAPID_SUBJECT,env.VAPID_PUBLIC_KEY,env.VAPID_PRIVATE_KEY)}
async function sendToDevice(env,deviceId,payload){configurePush(env);const list=await env.MAYAP_DATA.list({prefix:`sub:${deviceId}:`});let sent=0,removed=0;for(const key of list.keys){const raw=await env.MAYAP_DATA.get(key.name);if(!raw)continue;try{await webpush.sendNotification(JSON.parse(raw),JSON.stringify({...payload,deviceId,url:`/?device=${encodeURIComponent(deviceId)}`}));sent++}catch(error){const code=error?.statusCode||0;if(code===404||code===410){await env.MAYAP_DATA.delete(key.name);removed++}else console.error("push failed",deviceId,code,error?.message)}}return{sent,removed}}
async function enroll(request,env,origin){if(request.headers.get("X-Setup-Code")!==env.ENROLLMENT_KEY)return json({ok:false,error:"Mã cài đặt Worker không đúng"},401,origin);const body=await readJson(request),id=cleanId(body.deviceId),key=String(body.deviceKey||"");if(!id||key.length<16)return json({ok:false,error:"ID hoặc khóa thiết bị không hợp lệ"},400,origin);const current=await getDevice(env,id);const record={id,name:String(body.name||current?.name||id).slice(0,64),keyHash:await sha256(key),offlineAfterSec:Math.max(120,Math.min(3600,Number(body.offlineAfterSec)||180)),lastSeen:current?.lastSeen||0,offlineNotified:false,createdAt:current?.createdAt||Date.now()};await env.MAYAP_DATA.put(`dev:${id}`,JSON.stringify(record));return json({ok:true,enrolled:true,id},200,origin)}
async function subscribe(request,env,origin){const body=await readJson(request),auth=await authDevice(request,env,body);if(!auth)return json({ok:false,error:"ID hoặc khóa thiết bị không đúng"},401,origin);const sub=body.subscription;if(!sub?.endpoint)return json({ok:false,error:"Thiếu PushSubscription"},400,origin);const subId=(await sha256(sub.endpoint)).slice(0,32);await env.MAYAP_DATA.put(`sub:${auth.id}:${subId}`,JSON.stringify(sub));return json({ok:true,name:auth.dev.name,deviceId:auth.id},200,origin)}
async function heartbeat(request,env,origin){const body=await readJson(request),auth=await authDevice(request,env,body);if(!auth)return json({ok:false,error:"Thiết bị không được xác thực"},401,origin);auth.dev.lastSeen=Date.now();auth.dev.offlineNotified=false;auth.dev.name=String(body.name||auth.dev.name||auth.id).slice(0,64);auth.dev.offlineAfterSec=Math.max(120,Math.min(3600,Number(body.offlineAfterSec)||auth.dev.offlineAfterSec||180));auth.dev.last={temperature:body.temperature,humidity:body.humidity,state:body.state};await env.MAYAP_DATA.put(`dev:${auth.id}`,JSON.stringify(auth.dev));return json({ok:true,serverTime:Date.now()},200,origin)}
async function alert(request,env,origin){const body=await readJson(request),auth=await authDevice(request,env,body);if(!auth)return json({ok:false,error:"Thiết bị không được xác thực"},401,origin);auth.dev.lastSeen=Date.now();auth.dev.offlineNotified=false;await env.MAYAP_DATA.put(`dev:${auth.id}`,JSON.stringify(auth.dev));const payload={title:String(body.title||"Cảnh báo máy ấp trứng").slice(0,100),message:String(body.message||"").slice(0,300),type:String(body.type||"alert").slice(0,40),severity:String(body.severity||"warning").slice(0,20),tag:`mayap-${auth.id}-${body.type||"alert"}`,temperature:body.temperature,humidity:body.humidity};const result=await sendToDevice(env,auth.id,payload);return json({ok:true,...result},200,origin)}
async function checkOffline(env){const now=Date.now(),list=await env.MAYAP_DATA.list({prefix:"dev:"});for(const key of list.keys){const raw=await env.MAYAP_DATA.get(key.name);if(!raw)continue;const dev=JSON.parse(raw),limit=(dev.offlineAfterSec||180)*1000;if(dev.lastSeen&&now-dev.lastSeen>limit&&!dev.offlineNotified){await sendToDevice(env,dev.id,{title:"ESP32 MẤT KẾT NỐI",message:`${dev.name||dev.id} không gửi heartbeat trong ${Math.round(limit/60000)} phút.`,type:"device_offline",severity:"critical",tag:`mayap-${dev.id}-offline`});dev.offlineNotified=true;await env.MAYAP_DATA.put(key.name,JSON.stringify(dev))}}}
export default{async fetch(request,env){const origin=allowedOrigin(request,env);if(request.method==="OPTIONS")return json({},204,origin);const url=new URL(request.url);try{if(url.pathname==="/api/vapid-public-key"&&request.method==="GET")return json({publicKey:env.VAPID_PUBLIC_KEY},200,origin);if(url.pathname==="/api/device/enroll"&&request.method==="POST")return enroll(request,env,origin);if(url.pathname==="/api/subscribe"&&request.method==="POST")return subscribe(request,env,origin);if(url.pathname==="/api/device/heartbeat"&&request.method==="POST")return heartbeat(request,env,origin);if(url.pathname==="/api/device/alert"&&request.method==="POST")return alert(request,env,origin);if(url.pathname==="/health")return json({ok:true,time:Date.now()},200,origin);return json({ok:false,error:"Not found"},404,origin)}catch(error){console.error(error);return json({ok:false,error:"Worker error"},500,origin)}},async scheduled(event,env,ctx){ctx.waitUntil(checkOffline(env))}};